### PR TITLE
Update secret_weights.yml

### PR DESCRIPTION
**Pull request by vorkathbruh**
## About the PR

Remove zombie weight and add it to Revolutionaries. (5% zombie -> 0% zombie | 5% revs -> 10% revs)

## Why / Balance

zombies sucks

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by TraumaStationOfficial** [comment]
Not gonna Lie Bro, I fucking Hate Revs. I'm gonna go ask for a second opinion

**Comment by JoeHammad1844** [comment]
zombies is fun, i like the tension, desperate fights and rush to make a weapon before everybody turns

**Comment by JoeHammad1844** [comment]
also, zombies and revs just end too late, revs should end as soon as all the heads/headrevs are dead instead of a shuttle call, and zombies should end when everybody who is infected is dead (including people who haven't turned yet)

**Comment by JoeHammad1844** [comment]
survival should be sacrificed for revs instead of zombies, survival is just boring

**Comment by vorkathbruh** [comment]
agree, fuck survival

**Comment by Sailzington** [comment]
Why not make Zombies better if they suck? Maybe Give II their own coms channel so everyone can actually work together, I would love to see Revs get more weight but maybe take from survival or basic syndicates instead of zombies

**Review by TraumaStationOfficial — CHANGES_REQUESTED** [review]
Take the 5% from Survival, not Zombies. 

Other than That it was approved by Vote

**Comment by vorkathbruh** [comment]
The requested changes have been made.

**Pull request merged**
